- name: Update and upgrade installed packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: no
  loop:
    - git
    - python
    - python3
    - python3-dev
    - python3-pip

- block:
  - name: Clone project
    git:
      repo: git@github.com:victorfsf/talk-ansible-django.git
      dest: '{{ app_dir }}'
      accept_hostkey: yes

  - name: Create virtualenv
    command: python3 -m venv venv
    args:
      chdir: '{{ app_dir }}'

  become_user: '{{ user }}'
