
- name: Copy nginx app file
  template:
    src: nginx-app.j2
    dest: /etc/nginx/sites-available/app
    owner: '{{ user }}'
  notify: Link sites-available to sites-enabled

- name: Check the config syntax
  command: nginx -t
  notify: Restart nginx
