
- name: Setup app
  hosts: production
  remote_user: '{{ user }}'
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: base
      tags:
        - base
    - role: django
      tags:
        - django
    - role: uwsgi
      tags:
        - uwsgi
    - role: nginx
      tags:
        - nginx
