
- name: Create uwsgi sites folder
  file:
    path: '{{ uwsgi_sites_dir }}'
    state: directory
    owner: '{{ user }}'

- name: Copy uwsgi site file
  template:
    src: uwsgi-app.ini.j2
    dest: '{{ uwsgi_sites_dir }}/app.ini'
    owner: '{{ user }}'

- name: Copy systemd unit file for uwsgi
  template:
    src: app.service.j2
    dest: /etc/systemd/system/djangoapp.service
    owner: '{{ user }}'

- name: Make socket folder for uwsgi
  file:
    path: '{{ uwsgi_sock_dir }}'
    state: directory
    owner: '{{ user }}'

- name: Restart app
  systemd:
    name: djangoapp
    daemon_reload: yes
    enabled: yes
    state: restarted
